name: Ahoy Dev-Build for ESP8266/ESP32

on:
  push:
    branches: development*
    paths-ignore:
    - '**.md' # Do no build on *.md changes

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.repository == 'lumapu/ahoy' && github.ref_name == 'development03'
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3

  build-en:
    needs: check
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - esp8266
          - esp8266-prometheus
          - esp8285
          - esp32-wroom32
          - esp32-wroom32-prometheus
          - esp32-wroom32-ethernet
          - esp32-s2-mini
          - esp32-c3-mini
          - opendtufusion
          - opendtufusion-ethernet
    steps:
    - uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install setuptools --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO
      run:  pio run -d src -e ${{ matrix.variant }}

    - name: Rename Firmware
      run: python scripts/getVersion.py ${{ matrix.variant }} >> $GITHUB_OUTPUT

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-${{ matrix.variant }}
        path: firmware/*

  build-de:
    needs: check
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - esp8266-de
          - esp8266-prometheus-de
          - esp8285-de
          - esp32-wroom32-de
          - esp32-wroom32-prometheus-de
          - esp32-wroom32-ethernet-de
          - esp32-s2-mini-de
          - esp32-c3-mini-de
          - opendtufusion-de
          - opendtufusion-ethernet-de
    steps:
    - uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install setuptools --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO
      run:  pio run -d src -e ${{ matrix.variant }}

    - name: Rename Firmware
      run: python scripts/getVersion.py ${{ matrix.variant }} >> $GITHUB_OUTPUT

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-${{ matrix.variant }}
        path: firmware/*

  deploy:
    needs: [build-en, build-de]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: Copy boot_app0.bin
    #  run: cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin src/.pio/build/opendtufusion/ota.bin

    - name: Get Artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: firmware

    - name: Get Version from code
      id: version_name
      run: python scripts/getVersion.py ${{ matrix.variant }} >> $GITHUB_OUTPUT

    - name: Set Version
      uses: cschleiden/replace-tokens@v1
      with:
        files: tools/esp8266/User_Manual.md
      env:
          VERSION: ${{ steps.version_name.outputs.name }}

    - name: Rename firmware directory
      run: mv firmware ${{ steps.version_name.outputs.name }}

    - name: Deploy
      uses: nogsantos/scp-deploy@master
      with:
        src: ${{ steps.version_name.outputs.name }}/
        host: ${{ secrets.FW_SSH_HOST }}
        remote: ${{ secrets.FW_SSH_DIR }}/dev
        port: ${{ secrets.FW_SSH_PORT }}
        user: ${{ secrets.FW_SSH_USER }}
        key: ${{ secrets.FW_SSH_KEY }}
